SHELL := /bin/bash

.PHONY: all
all: \
	buf-lint \
	buf-generate \

include tools/buf/rules.mk
include tools/semantic-release/rules.mk

build/protoc-gen-go: go.mod
	$(info [$@] building binary...)
	@go build -o $@ google.golang.org/protobuf/cmd/protoc-gen-go

.PHONY: clean
clean:
	$(info [$@] removing build files...)
	@rm -rf build

.PHONY: buf-lint
buf-lint: $(buf)
	$(info [$@] linting protobuf schemas...)
	@cd internal/examples/proto && $(buf) lint

.PHONY: buf-generate
buf-generate: $(buf) build/protoc-gen-go
	$(info [$@] generating protobuf stubs...)
	@rm -rf internal/examples/proto/gen
	@cd internal/examples/proto && $(buf) generate --path einride
